name: Paper

on:
    push:
      branches:
        - main
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  paper:
    name: Build paper
    runs-on: self-hosted-runner-deployment-phg78-w68m5

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - run: ninja paper

      - uses: actions/upload-artifact@v4
        with:
          name: paper-latex
          path: paper-latex/main.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: paper-typst
          path: paper-typst/main.pdf

      - name: Upload paper to release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release delete --cleanup-tag -y latest || true
          mkdir out
          cp paper-latex/main.pdf out/latex.pdf
          cp paper-typst/main.pdf out/typst.pdf
          gh release create latest out/*

  check-figures:
    name: Check figures
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - run: ninja figures

      - name: Check if figures are up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Figures are out of date. Please rebuild figures and commit the changes."
            git diff --name-only
            exit 1
          fi
